namespace SourceGenerator.SGHelp
{
    internal record struct ClassInfo(string Code, string Compilation, string AddSource);

    public static class StringBuilderExtensions
    {
        public static void AppendLine(this StringBuilder builder, string value)
        {
            builder.Append(value);
            builder.Append(@"
            ");
        }
        static string Header()
        {
            var version = "ThisAssembly.Info.Version";
            var name = "ThisAssembly.Info.Title";
            var header = $$"""
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool {{name}}.
//     Runtime Version: {{version}}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
""";
            return header;
        }
    }
}