//HintName: TestClass2.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoMixins
// Version: {Removed}
// </auto-generated>
using System;
using Minerals.AutoMixins;
using Minerals.Test1;

namespace Minerals.Test2
{
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class TestClass2
    {
        // MixinType: TestMixin2
        [Obsolete] public int Property1_1 { get; set; } = 1;
        public int Field1_1 = 1;
        private int _filed2_1 = 2;
        public int Method1_1(int arg0, int arg1)
        {
            return arg0 + arg1;
        }
        protected int Method2_1(int arg0, int arg1)
        {
            return arg0 - arg1;
        }
    }
}