//HintName: TestClass.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoMixins
// Version: {Removed}
// </auto-generated>
using System;
using Minerals.AutoMixins;

namespace Minerals.Test1
{
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class TestClass
    {
        // MixinType: TestMixin
        [Obsolete] public int Property1 { get; set; } = 1;
        public int Field1 = 1;
        private int _filed2 = 2;
        public int Method1(int arg0, int arg1)
        {
            return arg0 + arg1;
        }
        protected int Method2(int arg0, int arg1)
        {
            return arg0 - arg1;
        }
    }
}