namespace Minerals.AutoMixins.Utils
{
    public static class CodeBuilderExtensions
    {
        public static CodeBuilder AddAutoGeneratedHeader(this CodeBuilder builder, Assembly assembly)
        {
            var title = assembly.GetCustomAttribute<AssemblyTitleAttribute>().Title;
            var version = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>().InformationalVersion;
            builder.Write("// <auto-generated>");
            builder.WriteLine("// This code was generated by a tool.");
            builder.WriteLine("// Name: ").Write(title);
            builder.WriteLine("// Version: ").Write(version);
            builder.WriteLine("// </auto-generated>");
            return builder;
        }

        public static CodeBuilder AddAutoGeneratedAttributes(this CodeBuilder builder, Type type)
        {
            if (type == typeof(ClassDeclarationSyntax)
            || type == typeof(StructDeclarationSyntax)
            || type == typeof(RecordDeclarationSyntax))
            {
                builder.WriteLine("[global::System.Diagnostics.DebuggerNonUserCode]");
                builder.WriteLine("[global::System.Runtime.CompilerServices.CompilerGenerated]");
                builder.WriteLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
            }
            else
            {
                builder.WriteLine("[global::System.Runtime.CompilerServices.CompilerGenerated]");
            }
            return builder;
        }
    }
}